import db from '@adonisjs/lucid/services/db'

export default class ItemSeeder {
  async run() {
    const items = [
      // === OFFENSIVE (8) ===
      {
        name_fr: 'Choix Rapide',
        description_fr: 'Augmente la Vitesse de ×1.5 mais verrouille sur la première attaque utilisée.',
        category: 'offensive',
        effect_type: 'choice_scarf',
        effect_value: JSON.stringify({ speed_mult: 1.5, choice_lock: true }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/choice-scarf.png',
        obtain_method: JSON.stringify(['gold_shop_weekly', 'floor_drop']),
        rarity: 'rare',
      },
      {
        name_fr: 'Choix Bande',
        description_fr: 'Augmente l\'Attaque de ×1.5 mais verrouille sur la première attaque utilisée.',
        category: 'offensive',
        effect_type: 'choice_band',
        effect_value: JSON.stringify({ atk_mult: 1.5, choice_lock: true }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/choice-band.png',
        obtain_method: JSON.stringify(['gold_shop_weekly', 'floor_drop']),
        rarity: 'rare',
      },
      {
        name_fr: 'Choix Lunettes',
        description_fr: 'Augmente l\'Atk Spé de ×1.5 mais verrouille sur la première attaque utilisée.',
        category: 'offensive',
        effect_type: 'choice_specs',
        effect_value: JSON.stringify({ spatk_mult: 1.5, choice_lock: true }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/choice-specs.png',
        obtain_method: JSON.stringify(['gold_shop_weekly', 'floor_drop']),
        rarity: 'rare',
      },
      {
        name_fr: 'Vie-Orbe',
        description_fr: 'Augmente les dégâts de ×1.3 mais inflige 10% HP de recul après chaque attaque.',
        category: 'offensive',
        effect_type: 'life_orb',
        effect_value: JSON.stringify({ damage_mult: 1.3, recoil_ratio: 0.1 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/life-orb.png',
        obtain_method: JSON.stringify(['gold_shop_weekly', 'floor_drop']),
        rarity: 'epic',
      },
      {
        name_fr: 'Griffe Dure',
        description_fr: 'Augmente les dégâts des attaques au contact de ×1.3.',
        category: 'offensive',
        effect_type: 'hard_claw',
        effect_value: JSON.stringify({ contact_damage_mult: 1.3 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/razor-claw.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Expert Ceinture',
        description_fr: 'Augmente de ×1.2 les dégâts des attaques super efficaces.',
        category: 'offensive',
        effect_type: 'expert_belt',
        effect_value: JSON.stringify({ super_effective_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/expert-belt.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Lentille de Mire',
        description_fr: 'Double le taux de coups critiques (1/12 au lieu de 1/24).',
        category: 'offensive',
        effect_type: 'scope_lens',
        effect_value: JSON.stringify({ crit_rate: 0.0833 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/scope-lens.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Ceinture Musclée',
        description_fr: 'Réduit de 50% les dégâts supplémentaires des coups critiques reçus.',
        category: 'offensive',
        effect_type: 'muscle_belt',
        effect_value: JSON.stringify({ reduce_crit_damage: 0.5 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/muscle-band.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      // === TYPE PLATES (18) ===
      {
        name_fr: 'Plaque Flamme',
        description_fr: 'Augmente la puissance des attaques Feu de ×1.2.',
        category: 'offensive',
        effect_type: 'type_plate',
        effect_value: JSON.stringify({ type: 'fire', type_boost_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/flame-plate.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Plaque Aqua',
        description_fr: 'Augmente la puissance des attaques Eau de ×1.2.',
        category: 'offensive',
        effect_type: 'type_plate',
        effect_value: JSON.stringify({ type: 'water', type_boost_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/splash-plate.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Plaque Tonnerre',
        description_fr: 'Augmente la puissance des attaques Électrik de ×1.2.',
        category: 'offensive',
        effect_type: 'type_plate',
        effect_value: JSON.stringify({ type: 'electric', type_boost_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/zap-plate.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Plaque Herbe',
        description_fri: 'Augmente la puissance des attaques Plante de ×1.2.',
        category: 'offensive',
        effect_type: 'type_plate',
        effect_value: JSON.stringify({ type: 'grass', type_boost_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/meadow-plate.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Plaque Givre',
        description_fr: 'Augmente la puissance des attaques Glace de ×1.2.',
        category: 'offensive',
        effect_type: 'type_plate',
        effect_value: JSON.stringify({ type: 'ice', type_boost_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/icicle-plate.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Plaque Combat',
        description_fr: 'Augmente la puissance des attaques Combat de ×1.2.',
        category: 'offensive',
        effect_type: 'type_plate',
        effect_value: JSON.stringify({ type: 'fighting', type_boost_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/fist-plate.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Plaque Toxique',
        description_fr: 'Augmente la puissance des attaques Poison de ×1.2.',
        category: 'offensive',
        effect_type: 'type_plate',
        effect_value: JSON.stringify({ type: 'poison', type_boost_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/toxic-plate.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Plaque Terre',
        description_fr: 'Augmente la puissance des attaques Sol de ×1.2.',
        category: 'offensive',
        effect_type: 'type_plate',
        effect_value: JSON.stringify({ type: 'ground', type_boost_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/earth-plate.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Plaque Vol',
        description_fr: 'Augmente la puissance des attaques Vol de ×1.2.',
        category: 'offensive',
        effect_type: 'type_plate',
        effect_value: JSON.stringify({ type: 'flying', type_boost_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sky-plate.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Plaque Psy',
        description_fr: 'Augmente la puissance des attaques Psy de ×1.2.',
        category: 'offensive',
        effect_type: 'type_plate',
        effect_value: JSON.stringify({ type: 'psychic', type_boost_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/mind-plate.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Plaque Insecte',
        description_fr: 'Augmente la puissance des attaques Insecte de ×1.2.',
        category: 'offensive',
        effect_type: 'type_plate',
        effect_value: JSON.stringify({ type: 'bug', type_boost_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/insect-plate.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Plaque Roc',
        description_fr: 'Augmente la puissance des attaques Roche de ×1.2.',
        category: 'offensive',
        effect_type: 'type_plate',
        effect_value: JSON.stringify({ type: 'rock', type_boost_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/stone-plate.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Plaque Spectre',
        description_fr: 'Augmente la puissance des attaques Spectre de ×1.2.',
        category: 'offensive',
        effect_type: 'type_plate',
        effect_value: JSON.stringify({ type: 'ghost', type_boost_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/spooky-plate.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Plaque Dragon',
        description_fr: 'Augmente la puissance des attaques Dragon de ×1.2.',
        category: 'offensive',
        effect_type: 'type_plate',
        effect_value: JSON.stringify({ type: 'dragon', type_boost_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/draco-plate.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Plaque Ténèbres',
        description_fr: 'Augmente la puissance des attaques Ténèbres de ×1.2.',
        category: 'offensive',
        effect_type: 'type_plate',
        effect_value: JSON.stringify({ type: 'dark', type_boost_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dread-plate.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Plaque Acier',
        description_fr: 'Augmente la puissance des attaques Acier de ×1.2.',
        category: 'offensive',
        effect_type: 'type_plate',
        effect_value: JSON.stringify({ type: 'steel', type_boost_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/iron-plate.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Plaque Fée',
        description_fr: 'Augmente la puissance des attaques Fée de ×1.2.',
        category: 'offensive',
        effect_type: 'type_plate',
        effect_value: JSON.stringify({ type: 'fairy', type_boost_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/pixie-plate.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Plaque Normal',
        description_fr: 'Augmente la puissance des attaques Normal de ×1.2.',
        category: 'offensive',
        effect_type: 'type_plate',
        effect_value: JSON.stringify({ type: 'normal', type_boost_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/blank-plate.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      // === DEFENSIVE (6) ===
      {
        name_fr: 'Restes',
        description_fr: 'Restaure 1/16 des PV max à chaque tour.',
        category: 'defensive',
        effect_type: 'leftovers',
        effect_value: JSON.stringify({ heal_ratio: 0.0625 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/leftovers.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'rare',
      },
      {
        name_fr: 'Coque-Écaille',
        description_fr: 'Augmente la Déf et la Déf Spé de ×1.5, réduit la Vitesse de ×0.5.',
        category: 'defensive',
        effect_type: 'shell_bell',
        effect_value: JSON.stringify({ def_mult: 1.5, spdef_mult: 1.5, speed_mult: 0.5 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/shell-bell.png',
        obtain_method: JSON.stringify(['gold_shop_weekly', 'floor_drop']),
        rarity: 'rare',
      },
      {
        name_fr: 'Baie Sitrus',
        description_fr: 'Restaure 25% des PV quand les PV passent sous 50%.',
        category: 'defensive',
        effect_type: 'sitrus_berry',
        effect_value: JSON.stringify({ heal_ratio: 0.25, hp_threshold: 0.5, one_time: true }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/sitrus-berry.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'common',
      },
      {
        name_fr: 'Écaille Bleue',
        description_fr: 'Augmente la Déf, Déf Spé et Vitesse de ×1.5 si les PV sont sous 50%.',
        category: 'defensive',
        effect_type: 'blue_scale',
        effect_value: JSON.stringify({ def_mult: 1.5, spdef_mult: 1.5, speed_mult: 1.5, hp_threshold: 0.5 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/deep-sea-scale.png',
        obtain_method: JSON.stringify(['gold_shop_weekly', 'floor_drop']),
        rarity: 'rare',
      },
      {
        name_fr: 'Baie Lum',
        description_fr: 'Soigne n\'importe quel statut négatif. Usage unique.',
        category: 'defensive',
        effect_type: 'lum_berry',
        effect_value: JSON.stringify({ cure_status: true, one_time: true }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lum-berry.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'common',
      },
      {
        name_fr: 'Ceinture Vaillante',
        description_fr: 'Réduit les dégâts reçus de 25% quand les PV sont sous 50%.',
        category: 'defensive',
        effect_type: 'assault_vest',
        effect_value: JSON.stringify({ atk_mult: 1.1, spatk_mult: 1.1, def_mult: 0.9, spdef_mult: 0.9 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/assault-vest.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'uncommon',
      },
      // === UTILITY (4) ===
      {
        name_fr: 'Herbe Miracle',
        description_fr: 'Augmente la Vitesse de ×1.2.',
        category: 'utility',
        effect_type: 'miracle_seed',
        effect_value: JSON.stringify({ speed_mult: 1.2 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/miracle-seed.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'common',
      },
      {
        name_fr: 'Ballon',
        description_fr: 'Rend le porteur immunisé aux attaques Sol. Éclate quand il est touché.',
        category: 'utility',
        effect_type: 'air_balloon',
        effect_value: JSON.stringify({ ground_immunity: true }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/air-balloon.png',
        obtain_method: JSON.stringify(['gold_shop_weekly', 'floor_drop']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Loupe',
        description_fr: 'Augmente la précision de toutes les attaques de ×1.1.',
        category: 'utility',
        effect_type: 'magnifier',
        effect_value: JSON.stringify({ accuracy_mult: 1.1 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/wide-lens.png',
        obtain_method: JSON.stringify(['gold_shop', 'floor_drop']),
        rarity: 'common',
      },
      {
        name_fr: 'Graine Lumineuse',
        description_fr: 'Augmente légèrement tous les stats de ×1.05.',
        category: 'utility',
        effect_type: 'bright_powder',
        effect_value: JSON.stringify({ all_stats_mult: 1.05 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/bright-powder.png',
        obtain_method: JSON.stringify(['floor_drop']),
        rarity: 'epic',
      },
      // === BONBONS / CANDIES (3) ===
      {
        name_fr: 'Bonbon Rare',
        description_fr: 'Augmente de 1 le niveau du Pokémon cible.',
        category: 'candy',
        effect_type: 'rare_candy',
        effect_value: JSON.stringify({ levels: 1 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rare-candy.png',
        obtain_method: JSON.stringify(['floor_drop', 'dungeon_reward', 'raid_reward']),
        rarity: 'rare',
      },
      {
        name_fr: 'Bonbon Exp. L',
        description_fr: 'Donne 30 000 points d\'expérience au Pokémon cible.',
        category: 'candy',
        effect_type: 'exp_candy_l',
        effect_value: JSON.stringify({ xp: 30000 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/exp-candy-l.png',
        obtain_method: JSON.stringify(['floor_drop', 'dungeon_reward']),
        rarity: 'uncommon',
      },
      {
        name_fr: 'Bonbon Exp. XL',
        description_fr: 'Donne 100 000 points d\'expérience au Pokémon cible.',
        category: 'candy',
        effect_type: 'exp_candy_xl',
        effect_value: JSON.stringify({ xp: 100000 }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/exp-candy-xl.png',
        obtain_method: JSON.stringify(['floor_drop', 'dungeon_reward', 'raid_reward']),
        rarity: 'rare',
      },
      // === PASSIVE (3) ===
      {
        name_fr: 'Orbe Toxique',
        description_fr: 'Empoisonne gravement le porteur après 3 actions.',
        category: 'passive',
        effect_type: 'toxic_orb',
        effect_value: JSON.stringify({ trigger_actions: 3, inflict_status: 'badly_poisoned' }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/toxic-orb.png',
        obtain_method: JSON.stringify(['floor_drop']),
        rarity: 'epic',
      },
      {
        name_fr: 'Orbe Flamme',
        description_fr: 'Brûle le porteur après 3 actions.',
        category: 'passive',
        effect_type: 'flame_orb',
        effect_value: JSON.stringify({ trigger_actions: 3, inflict_status: 'burn' }),
        sprite_url: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/flame-orb.png',
        obtain_method: JSON.stringify(['floor_drop']),
        rarity: 'epic',
      },
    ]

    // Remove typo field description_fri from item if present
    const cleaned = items.map((item: any) => {
      const { description_fri, ...rest } = item as any
      return rest
    })

    await db.rawQuery(`
      INSERT INTO items (name_fr, description_fr, category, effect_type, effect_value, sprite_url, obtain_method, rarity)
      VALUES ${cleaned.map(() => '(?, ?, ?, ?, ?::jsonb, ?, ?::jsonb, ?)').join(', ')}
      ON CONFLICT DO NOTHING
    `, cleaned.flatMap(i => [
      i.name_fr,
      i.description_fr ?? '',
      i.category,
      i.effect_type,
      i.effect_value,
      i.sprite_url ?? '',
      i.obtain_method,
      i.rarity,
    ]))

    console.log(`[ItemSeeder] Seeded ${cleaned.length} items`)
  }
}
