events {
    worker_connections 1024;
}

http {
    upstream api {
        server api:3333;
    }

    upstream web {
        server web:3000;
    }

    upstream admin {
        server admin:3001;
    }

    # Game frontend
    server {
        listen 80;
        server_name pokegrind.fr www.pokegrind.fr;

        location /api {
            proxy_pass http://api;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        location / {
            proxy_pass http://web;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }

    # Admin panel
    server {
        listen 80;
        server_name admin.pokegrind.fr;

        # TODO: IP whitelist in production
        # allow 1.2.3.4;
        # deny all;

        location / {
            proxy_pass http://admin;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}
